### ISSUE TITLE
UX of map with mouse

### ISSUE THREAD

**Issue by kiesel** [thekid/dialog#64]
When opening a post, on the page below the header can be a map. When the mouse is positioned over the map, all mouse-wheel-down actions zoom out the map. This may come as a surprise when a user was not aware the mouse was positioned over the map.

(IIRC Google maps has done so, too, but opted out and only zoom when also holding down the Ctrl key - maybe OSN has a similar option).

**Comment by thekid** [comment]
https://github.com/openlayers/openlayers/issues/7666 seems to have the solution for this

**Comment by thekid** [comment]
Another idea is to use [maps that do not interrupt page scrolling](https://openlayers.org/en/main/examples/page-scroll.html):

> To perform wheel/trackpad zoom and drag-pan actions only when the map has the focus, configure your map div with a tabindex attribute.

This would only need the following changes applied:

```diff
diff --git a/src/main/handlebars/content.handlebars b/src/main/handlebars/content.handlebars
index a412a9b..7d718d2 100755
--- a/src/main/handlebars/content.handlebars
+++ b/src/main/handlebars/content.handlebars
@@ -27,7 +27,7 @@ parent: feed
         {{count item.views '' '(Eine Ansicht)' '(# Ansichten)'}}
       </div>
 
-      <div id="map">
+      <div id="map" tabindex="1">
         <div class="popup"></div>
       </div>
 
diff --git a/src/main/handlebars/journey.handlebars b/src/main/handlebars/journey.handlebars
index f28055e..a0a424d 100755
--- a/src/main/handlebars/journey.handlebars
+++ b/src/main/handlebars/journey.handlebars
@@ -29,7 +29,7 @@ parent: feed
       </div>
       {{> partials/images in=journey first='true' style='overview'}}
 
-      <div id="map">
+      <div id="map" tabindex="1">
         <div class="popup"></div>
       </div>
 
diff --git a/src/main/handlebars/journeys.handlebars b/src/main/handlebars/journeys.handlebars
index bd5fa43..bb6489b 100755
--- a/src/main/handlebars/journeys.handlebars
+++ b/src/main/handlebars/journeys.handlebars
@@ -11,7 +11,7 @@
     {{/with}}
   {{/inline}}
   {{#*inline "main"}}
-    <div id="map" class="full">
+    <div id="map" class="full" tabindex="1">
       <div class="popup"></div>
     </div>
 
```

**Comment by kiesel** [comment]
Works as expected with tabindex now - nice & easy solution, I guess.

**Comment by thekid** [comment]
Released in https://github.com/thekid/dialog/releases/tag/v2.6.0
